name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest pnpm@latest
      - name: Build Project Artifacts
        run: |
          pnpm install
          pnpm build
      - name: Creating release folder
        run: |
          zip -r public.zip dist
          mkdir -p dist/release
          mv public.zip dist/release/latest.zip
          echo $GITHUB_SHA > dist/release/latest.txt
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}